spring:
  mvc:
    throw-exception-if-no-handler-found: true #핸들러를 찾지 못했을 때 예외를 던질지 여부를 결정
    static-path-pattern: /static/**

  activate:
    on-profile: local

  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/testDB
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
      format_sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  thymeleaf:
    config.activate.on-profile: local
    prefix: classpath:/templates/
    suffix: html